#!/usr/bin/env python

# Gtk
import gtk

# Bo-Keep
from bokeep.gui.mainwindow import MainWindow
from bokeep.book_transaction import \
     new_transaction_committing_thread

# python
from optparse import OptionParser

def bokeep_main():
    op = OptionParser()
    op.add_option("-c", "--config", dest="configfile",
                  default=None,
                  help="specify configuration file" )
    (options, args) = op.parse_args()
    window = MainWindow(options, args)
    gtk.main()
    
if __name__ == "__main__":
    bokeep_main() # should really look at return value and set exit status
