#!/usr/bin/env python

# python
from os.path import dirname, abspath, join, exists
from sys import path

# if there is a src sub-directory, we must be running bo-keep from
# a source tree, so add that src dir to the search path
SRC_PATH = join(abspath(dirname(__file__)), "src")
if exists(SRC_PATH):
    path.append( SRC_PATH )

# Gtk
import gtk

# Bo-Keep
from bokeep.gui.mainwindow import MainWindow

# python
from optparse import OptionParser

def bokeep_main():
    op = OptionParser()
    op.add_option("-c", "--config", dest="configfile",
                  default=None,
                  help="specify configuration file" )
    (options, args) = op.parse_args()
    window = MainWindow(options, args)
    gtk.main()
    
if __name__ == "__main__":
    bokeep_main() # should really look at return value and set exit status
